mongo:
  db_name: "ipma"
  collections:
    observations: "ansiao"
    precipitation: "precipitation"
    evapotranspiration: "evapotranspiration"

location_coordinates: "39.940528, -8.168023"

ipma: 
  district: "leiria"
  municipality: "pedrogao-grande"
  dico: 1013
  closest_station:
    location: "ansiao"
    idStation: "1210716"
  closest_region:
    idAreaAviso: "CBR"
    globalIdLocal: 1060300
  closest_regions:
    - idRegiao: 1
      idAreaAviso: "CBR"
      idConcelho: 3
      globalIdLocal: 1060300
      latitude: "40.2081"
      idDistrito: 6
      local: "Coimbra"
      longitude: "-8.4194"
      distance: "36km NW" # add this hardcoded
      acronym: "C" # add this hardcoded
    - idRegiao: 1
      idAreaAviso: "LRA"
      idConcelho: 9
      globalIdLocal: 1100900
      latitude: "39.7473"
      idDistrito: 10
      local: "Leiria"
      longitude: "-8.8069"
      distance: "58km WSW" # add this hardcoded
      acronym: "L" # add this hardcoded
    - idRegiao: 1
      idAreaAviso: "CBO"
      idConcelho: 2
      globalIdLocal: 1050200
      latitude: "39.8217"
      idDistrito: 5
      local: "Castelo Branco"
      longitude: "-7.4957"
      distance: "59km ESE" # add this hardcoded
      acronym: "CB" # add this hardcoded

meteoblue:
  closest_places:
    - name: "Troviscais Fundeiros"
      distance_km: 0.78
      iso2: "PT"
      country: "Portugal"
      admin1: "Leiria District"
      lat: 39.9337
      lon: -8.16585
      asl: 391
      featureClass: "P"
      featureCode: "PPL"
      url: "troviscais-fundeiros_portugal_2262489"
      id: 2262489
      

    - name: "Mosteiro"
      distance_km: 1.51
      iso2: "PT"
      country: "Portugal"
      admin1: "Leiria District"
      lat: 39.9377
      lon: -8.18527
      asl: 306
      featureClass: "P"
      featureCode: "PPL"
      url: "mosteiro_portugal_2265709"
      id: 2265709

    - name: "Pedr처g찾o Grande"
      distance_km: 3.10
      iso2: "PT"
      country: "Portugal"
      admin1: "Leiria District"
      lat: 39.9184
      lon: -8.1459
      asl: 400
      featureClass: "P"
      featureCode: "PPLA2"
      url: "pedr처g찾o-grande_portugal_2265000"
      id: 2265000


